# Generated by Django 4.1.3 on 2022-12-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='samuele-bertoli-C0gX9PFh07Q-unsplash.jpg', upload_to='user_images'),
        ),
    ]
