# Generated by Django 4.1.3 on 2024-03-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopUser', '0004_verifiedphone_verifiedemail_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedemail',
            name='timeout',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='verifiedphone',
            name='timeout',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
