# Generated by Django 4.1.3 on 2024-03-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopUser', '0005_alter_verifiedemail_timeout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
    ]
