# Generated by Django 4.1.3 on 2024-03-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopUser', '0006_remove_customuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dndmmeamv/image/upload/v1/images/user_images/7io30qysok731_mgewcf', null=True, upload_to='user_images'),
        ),
    ]
