# Generated by Django 4.1.3 on 2024-03-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopUser', '0007_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/djmtfxn8e/image/upload/v1711895043/istockphoto-1495088043-612x612_luc76o.jpg', null=True, upload_to='user_images'),
        ),
    ]
