# Generated by Django 4.1.3 on 2023-04-17 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_newsletteremails'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteremails',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
