# Generated by Django 4.1.3 on 2023-04-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_alter_like_id_alter_location_id_and_more'),
    ]

    operations = [
    ]
