# Generated by Django 4.1.3 on 2022-12-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_shopcategory_remove_shop_condition_remove_shop_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='shop',
        ),
        migrations.AddField(
            model_name='productphoto',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopapp.product'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShopPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_image')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.shop')),
            ],
        ),
    ]
