# Generated by Django 4.1.3 on 2022-12-09 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.location'),
        ),
    ]
