# Generated by Django 4.1.3 on 2022-12-09 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_alter_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.location'),
        ),
    ]
