# Generated by Django 4.1.3 on 2022-12-24 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopapp', '0008_remove_like_is_like_like_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(related_name='liked_products', through='shopapp.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
