# Generated by Django 4.1.3 on 2022-12-12 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_remove_product_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='ad_title',
        ),
    ]
