# Generated by Django 4.1.3 on 2022-12-26 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
