# Generated by Django 4.1.3 on 2022-12-28 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopphoto',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_images', to='shopapp.shop'),
        ),
    ]
