# Generated by Django 4.1.3 on 2023-03-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0015_alter_shopphoto_image_alter_shopphoto_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_images'),
        ),
    ]
