# Generated by Django 4.1.3 on 2023-03-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0016_productcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_posted',
        ),
    ]
