# Generated by Django 4.1.3 on 2023-03-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0018_product_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
