# Generated by Django 4.1.3 on 2023-03-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0019_goods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
