# Generated by Django 4.1.3 on 2023-03-17 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0020_delete_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ff',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
