# Generated by Django 4.1.3 on 2023-03-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0021_product_ff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ff',
        ),
    ]
